services:
  - type: web
    name: saju-destiny-system
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    region: singapore
